export const CREATE_FLIGHT = 'FLIGHT/CREATE_FLIGHT';
export const UPDATE_FLIGHT = 'FLIGHT/UPDATE_FLIGHT';
export const DELETE_FLIGHT = 'FLIGHT/DELETE_FLIGHT';

export const LOGIN_USER = 'AUTH/LOGIN_USER';
export const LOGOUT_USER = 'AUTH/LOGOUT_USER';
